name: flutter_solana_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  hex: ^0.2.0
  solana: ^0.31.0
  web3auth_flutter:
    git:
      url: https://github.com/web3auth/web3auth-flutter-sdk.git
      ref: feat/update_pnp_swift_dep
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
