name: Upload Flutter Android Quick Start build on appetize

on:
  pull_request:
    paths:
      - "./flutter/flutter-quick-start/**"

defaults:
  run:
    working-directory: ./flutter/flutter-quick-start/android

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Set execution flag for gradlew
        run: chmod +x gradlew

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk debug project
        run: ./gradlew assembleDebug

      - name: Upload to Appetize
        uses: appetizeio/github-action-appetize@v1.0.1
        with:
          apiToken: ${{ secrets.APPETIZE_SECRET_KEY }}
          publicKey: ${{ secrets.FLUTTER_ANDROID_QUICK_START_PUBLIC_KEY }}
          appFile: ./flutter/flutter-quick-start/build/app/outputs/apk/debug/app-debug.apk
          platform: "android"
